# Generated by Django 2.1 on 2018-08-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='is_buys',
        ),
    ]
